apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gcg1zymhh-python 
  janus-idp.io/tekton: gcg1zymhh-python
  backstage.io/kubernetes-id: gcg1zymhh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gcg1zymhh-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  