apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gcg1zymhh-python
  janus-idp.io/tekton: gcg1zymhh-python
  backstage.io/kubernetes-id: gcg1zymhh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gcg1zymhh-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
